import {StyleSheet, Dimensions} from 'react-native';
import colors from './colors';
module.exports = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    // backgroundColor: '#FCF9F2',
  },

  modalBackdrop: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    position: 'absolute',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  modal: {
    position: 'absolute',
    backgroundColor: colors.backgroundcolor,
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
    top: Dimensions.get('window').height * 0.1,
    width: Dimensions.get('window').width * 0.75,
    height: Dimensions.get('window').height * 0.5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    color: '#000',
  },
  imageModal: {
    width: Dimensions.get('window').width * 0.8,
    height: 200,
    // position: 'absolute',
    // backgroundColor: colors.purple,
  },
  textModal: {
    color: colors.textcolor,
    textAlign: 'center',
    width: Dimensions.get('window').width * 0.6,
    padding: 20,
    fontSize: 18,
  },

  buttonModal: {
    backgroundColor: colors.maincolor,
    padding: 15,
    borderRadius: 5,
    width: Dimensions.get('window').width * 0.4,
  },
  textButtonModal: {color: '#fff', textAlign: 'center', fontSize: 18},
  container: {
    // flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    // borderRadius: 10,
    overflow: 'hidden',
    // margin: 20,
    // marginTop: 50,
  },
  map: {
    width: Dimensions.get('window').width * 1,
    height: Dimensions.get('window').height * 1,

    // width: 50,
    // height: 50
  },
  absoluteText: {
    position: 'absolute',
    top: -75,
    zIndex: 5,
    backgroundColor: colors.backgroundcolor,
    color: colors.textcolor,
    padding: 10,
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    borderRadius: 5,
    width: Dimensions.get('window').width * 0.7,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    color: '#000',
    borderRadius: 3,
  },

  layout: {
    alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: colors.backgroundColor,
  },
  center: {
    alignItems: 'center',
    justifyContent: 'center',
    height: Dimensions.get('window').height * 0.6,
    // backgroundColor: colors.purple,
  },
  bottemNav: {
    backgroundColor: colors.backgroundcolor,
    borderRadius: 5,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: Dimensions.get('window').width * 0.7,
    marginTop: 15,
    marginBottom: 15,
  },
  // button: {
  //   backgroundColor: colors.maincolor,
  //   padding: 10,
  //   borderRadius: 5,
  //   width: Dimensions.get('window').width * 0.2,
  // },
  button: {
    backgroundColor: colors.maincolor,
    width: Dimensions.get('window').width * 0.9,
    padding: 10,
    borderRadius: 7,
    marginBottom: 50,
  },
  buttonMedium: {
    backgroundColor: colors.maincolor,
    padding: 10,
    borderRadius: 5,
    width: Dimensions.get('window').width * 0.5,
  },
  buttonSmall: {
    backgroundColor: colors.maincolor,
    padding: 10,
    borderRadius: 5,
    width: Dimensions.get('window').width * 0.2,
  },
  buttonText: {
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    fontSize: 15,
  },
  title: {
    fontWeight: 'bold',
    fontSize: 30,
    color: colors.textcolor,
  },
  subtitle: {
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'left',
    color: colors.textcolor,
    marginBottom: 50,
  },
  // css for the bottem of the signup and login
  bottemText: {
    flexDirection: 'row',
    color: colors.textcolor,
    marginBottom: 25,
    borderTopColor: colors.secondarycolor,
    borderTopWidth: 5,
    paddingTop: 15,
    width: Dimensions.get('window').width * 0.9,
    justifyContent: 'center',
  },
  link: {
    textDecorationLine: 'underline',
  },
  error: {
    backgroundColor: colors.quatrarycolor,
    color: '#fff',
    padding: 10,
    width: Dimensions.get('window').width * 0.5,
    textAlign: 'center',
    borderRadius: 5,
  },
  //   buttonText: {
  //     textAlign: 'center',
  //     color: '#fff',
  //   },
  legendaContainter: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  progressText: {
    color: colors.maincolor,
    fontSize: 18,
    fontWeight: 'bold',
    margin: 10,
  },
  // title: {
  //   fontSize: 20,
  //   color: colors.textcolor,
  //   textAlign: 'center',
  // },
  titleSmall: {
    fontSize: 20,
    color: colors.textcolor,
    textAlign: 'center',
    width: Dimensions.get('window').width * 0.8,
  },
  label: {
    color: colors.textcolor,
  },
  seasonsBox: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  colordBorder: {
    borderRadius: 5,
    borderWidth: 2,
    borderColor: colors.maincolor,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 10,
    backgroundColor: '#fff',
    // marginLeft: 5,
    // borderTopColor: colors.firstColor,
    // borderRightColor: colors.secondColor,
    // borderBottomColor: colors.thirthColor,
    // borderLeftColor: colors.fourthColor,
  },
  textInput: {
    // width: Dimensions.get('window').width * 0.8,
    // height: 50,
    // paddingLeft: 15,
    // color: colors.textcolor,
    // borderRadius: 5,
    // borderWidth: 2,
    // borderColor: colors.maincolor,
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 4,
    // },
    // shadowOpacity: 0.32,
    // shadowRadius: 5.46,
    // elevation: 9,
    // borderRadius: 10,
    // backgroundColor: '#fff',
    // borderBottomColor: colors.secondarycolor,
    // borderBottomWidth: 5,
    width: Dimensions.get('window').width * 0.9,
    backgroundColor: '#eef2f5',
    padding: 10,
    borderRadius: 7,
    marginBottom: 10,
    color: colors.textcolor,
  },
  label: {
    color: colors.textcolor,
    paddingBottom: 5,
  },
  backbutton: {
    alignSelf: 'flex-start',
    marginLeft: 30,
    backgroundColor: '#fff',
    padding: 10,
    width: 50,
    borderRadius: 40,
  },
  textInputLong: {
    height: Dimensions.get('window').height * 0.2,
    paddingLeft: 15,
    paddingTop: 15,
    textAlignVertical: 'top',
  },
  instructions: {
    width: Dimensions.get('window').width * 0.8,
    // minHeight: Dimensions.get('window').height * 0.2,
    // flexBasis: Dimensions.get('window').height * 0.2,
    // height: Dimensions.get('window').height * 0.5,
  },
  map: {
    width: Dimensions.get('window').width * 1,
    height: Dimensions.get('window').height * 1,
  },
  shadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
  },
  ingredient: {
    fontSize: 20,
    // zIndex: 20,
    padding: 20,
    backgroundColor: colors.backgroundcolor,
    flexDirection: 'row',
  },
  text: {
    color: colors.textcolor,
    justifyContent: 'center',
    alignItems: 'center',
    // textAlign: 'center',
  },
  recipe: {
    flex: 1,
    position: 'absolute',

    marginTop: 300,
    // zIndex: 20,
    color: colors.textcolor,
    // backgroundColor: colors.pink,
    height: 500,
    width: 250,
  },
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagecontainer: {
    position: 'absolute',
    height: 200,
    zIndex: 2,
  },
  overlay: {
    zIndex: 3,
  },
  image: {
    width: Dimensions.get('window').width * 0.8,
    height: 250,
    // position: 'absolute',
    // backgroundColor: colors.purple,
  },
  titleText: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    zIndex: 4,
    fontWeight: 'bold',
    fontSize: 20,
    padding: 20,
  },
  timeText: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    zIndex: 4,
    fontWeight: 'bold',
    fontSize: 20,
    padding: 20,
  },
  backButton: {
    position: 'absolute',
    zIndex: 4,
    margin: 20,
  },
  arrowBackdrop: {
    position: 'absolute',
    padding: 20,
    backgroundColor: '#000',
    opacity: 0.4,
    borderRadius: 50,
  },
  arrow: {
    position: 'absolute',
    left: 10,
    top: 10,
    zIndex: 4,
    color: '#fff',
  },
  likeContainer: {
    position: 'absolute',
    right: 0,
    margin: 10,
  },

  titleBar: {
    width: Dimensions.get('window').width * 0.85,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    margin: 25,
    padding: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 9,
    borderRadius: 3,
    // position: 'absolute',
    height: 50,
    zIndex: 10,
    position: 'absolute',
    // top: 200,
  },
  barText: {
    color: colors.textcolor,
    fontWeight: 'bold',
  },
  blob: {
    width: Dimensions.get('window').width,
    height: 110,
    // marginBottom: -15,
    // zIndex: 10,
    // position: 'absolute',
    // top: 200,
  },
  loader: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    top: 250,
    width: 100,
    height: 100,
    borderRadius: 25,
    zIndex: 3,
    backgroundColor: '#fff',
  },
  loaderframe: {
    position: 'absolute',
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
    zIndex: 2,
    backgroundColor: '#C0C0C0',
    opacity: 0.4,
  },
});
